# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin 
  - linux
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386
  - goos: darwin
    goarch: arm
  - goos: darwin
    goarch: arm64
  - goos: windows
    goarch: arm
  - goos: windows
    goarch: arm
  - goos: windows
    goarch: arm64
  - goarch: arm64
    goarm: 6
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
